[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && npx http-server dist -p $PORT -a 0.0.0.0 --cors"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }
