services:
  - type: web
    name: quotation-app-fe
    env: node
    buildCommand: npm ci && npm run build && node verify-deployment.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
